[providers]
# Actualizado a Node 20 para alinear con package.json (engines.node = 20.x)
node = "20.x"

[phases.setup]
# Usa la versión de node 20.x en nixpacks
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"