[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/healthz"
healthcheckTimeout = 60

[env]
NODE_ENV = "production"
FAST_START = "true"
LOG_LEVEL = "info"